### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by cyclops24** [radiegtya/meteoris2#89]
Hi,
I saw that last commit is for 3 month ago. Is this project still active?

**Comment by jaredthirsk** [comment]
I am wondering this too.  Trying to decide between this and meteor-kitchen.  I am concerned that it looks like this one made a copy of the repo for v2 around the same time that activity stopped on v2.  Is this project somehow flawed in that it needs a revamp?  Or is it so good that it doesn't need more updates and there is not enough reason for v2?

**Comment by radiegtya** [comment]
Hi, the project is on pending state, because I am very busy nowadays.
Please use v1 only for production, and you are free to use v2 for development purpose.

Regards
