### ISSUE TITLE
Error when using CRUDSS Generator

### ISSUE THREAD

**Issue by elsopi** [radiegtya/meteoris2#91]
Hi, I just came across meteoris and i think i like it. I have watched the videos on youtube and now I want to try it out. 
So far, I've been able to clone and start the application, login as admin, create posts and all that. But, I am having issues using the CRUDSS Generator. If I want to create a new package, say "Jobs" , after filling all the required fields and submit, I get a success notification but nothing happens. On my console i see this error messages 

{ [Error: ENOENT, open 'c:\meteorapps\meteoris_demo\.meteor\local\build\programs\server\undefined\client\routers\pages.js']
I20151020-21:27:35.361(1)?   errno: 34,
I20151020-21:27:35.362(1)?   code: 'ENOENT',
I20151020-21:27:35.363(1)?   path: 'c:\\meteorapps\\meteoris_demo\\.meteor\\local\\build\\programs\\server\\undefined\\client\\routers\\pages.js' }
I20151020-21:27:35.365(1)? { [Error: ENOENT, mkdir 'c:\meteorapps\meteoris_demo\.meteor\local\build\programs\server\undefined\client\views\pages']
I20151020-21:27:35.365(1)?   errno: 34,
I20151020-21:27:35.367(1)?   path: 'c:\\meteorapps\\meteoris_demo\\.meteor\\local\\build\\programs\\server\\undefined\\client\\views\\pages' }............

Am i doing something wrong, can anyone help me out?

Thank you.

**Comment by radiegtya** [comment]
That because meteoris still not yet supporting windows. Please use ubuntu or mac.
